/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaForms;

import java.net.URL;
import javax.swing.*;
import functions.collegesTable;
import functions.programsTable;
import functions.studentTable;
import functions.studentForm;

/**
 *
 * @author John-Ronan Beira
 */
public class dashboardFrame extends javax.swing.JFrame {

    private static dashboardFrame instance;

    collegesTable collegesTableForm = new collegesTable();
    programsTable programsTableForm = new programsTable();
    studentTable studentTableForm = new studentTable();
    studentForm studentEnrollmentForm = new studentForm();

    /**
     * Creates new form dashboardFrame
     */
    public dashboardFrame() {
        instance = this;

        initComponents();
        URL iconUrl = getClass().getResource("/resources/images/tabIcon.png");
        ImageIcon logo = new ImageIcon(iconUrl);
        setIconImage(logo.getImage());

        studentEnrollmentForm.setStudentTableReference(studentTableForm);
        studentTableForm.setStudentFormReference(studentEnrollmentForm);
        programsTableForm.setStudentFormReference(studentTableForm);
        programsTableForm.setCollegeTableReference(collegesTableForm);
        collegesTableForm.setProgramsTableReference(programsTableForm);
        collegesTableForm.setStudentFormReference(studentTableForm);
    }

    //setters
    public void setToggleFormButtonn(String text) {
        toggleFormButton.setText(text);
    }

    //getters
    public javax.swing.JToggleButton getToggleFormButton() {
        return toggleFormButton;
    }

    public javax.swing.JTabbedPane getDashboardTabs() {
        return dashboardTabs;
    }

    //static method
    public static dashboardFrame getInstance() {
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        dashboardTabs = new javax.swing.JTabbedPane();
        studentInformationContainer = new javax.swing.JPanel();
        enrollmentFormsContainer = new javax.swing.JPanel();
        formPanelHolder = new javax.swing.JPanel();
        toggleFormsPanelHolder = new javax.swing.JPanel();
        toggleFormButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        managementContainer = new javax.swing.JPanel();
        managementTabbedPanes = new javax.swing.JTabbedPane();
        collegesContainer = new javax.swing.JPanel();
        programsContainer = new javax.swing.JPanel();
        greetingPanel = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        greetingLabel = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Database MySQL Integrated");
        setMinimumSize(new java.awt.Dimension(1050, 750));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        dashboardTabs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dashboardTabs.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        dashboardTabs.setDoubleBuffered(true);
        dashboardTabs.setName(""); // NOI18N

        studentInformationContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        studentInformationContainer.setLayout(new java.awt.GridLayout(1, 0));
        dashboardTabs.addTab("     Student Data Information     ", studentInformationContainer);
        studentInformationContainer.removeAll();

        studentInformationContainer.add(studentTableForm.showTable());

        studentInformationContainer.repaint();
        studentInformationContainer.revalidate();
        studentInformationContainer.getAccessibleContext().setAccessibleParent(this);

        enrollmentFormsContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        enrollmentFormsContainer.setLayout(new java.awt.GridBagLayout());

        formPanelHolder.setLayout(new java.awt.GridLayout(1, 0));

        formPanelHolder.removeAll();

        formPanelHolder.add(studentEnrollmentForm.showForm());

        formPanelHolder.repaint();
        formPanelHolder.revalidate();

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        enrollmentFormsContainer.add(formPanelHolder, gridBagConstraints);

        toggleFormsPanelHolder.setLayout(new java.awt.GridBagLayout());

        toggleFormButton.setBackground(new java.awt.Color(153, 255, 153));
        toggleFormButton.setFont(toggleFormButton.getFont().deriveFont(toggleFormButton.getFont().getStyle() | java.awt.Font.BOLD));
        toggleFormButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/add.png"))); // NOI18N
        toggleFormButton.setText("Enrollment Form");
        toggleFormButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        toggleFormButton.setDoubleBuffered(true);
        toggleFormButton.setFocusCycleRoot(true);
        toggleFormButton.setMaximumSize(null);
        toggleFormButton.setMinimumSize(null);
        toggleFormButton.setOpaque(true);
        toggleFormButton.setPreferredSize(new java.awt.Dimension(180, 30));
        toggleFormButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/loading-arrow.png"))); // NOI18N
        toggleFormButton.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toggleFormsPanelHolder.add(toggleFormButton, gridBagConstraints);

        jLabel1.setText("You're currently set in:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toggleFormsPanelHolder.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.6;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        toggleFormsPanelHolder.add(filler3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        enrollmentFormsContainer.add(toggleFormsPanelHolder, gridBagConstraints);

        dashboardTabs.addTab("     Enrollment Forms     ", enrollmentFormsContainer);

        managementContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        managementContainer.setLayout(new java.awt.GridBagLayout());

        managementTabbedPanes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        managementTabbedPanes.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        managementTabbedPanes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        collegesContainer.setLayout(new java.awt.GridLayout(1, 0));
        managementTabbedPanes.addTab("     Colleges     ", collegesContainer);
        collegesContainer.removeAll();

        collegesContainer.add(collegesTableForm.showTable());

        collegesContainer.repaint();
        collegesContainer.revalidate();

        programsContainer.setLayout(new java.awt.GridLayout(1, 0));
        managementTabbedPanes.addTab("     Programs     ", programsContainer);
        programsContainer.removeAll();

        programsContainer.add(programsTableForm.showTable());

        programsContainer.repaint();
        programsContainer.revalidate();

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        managementContainer.add(managementTabbedPanes, gridBagConstraints);

        dashboardTabs.addTab("     College Management     ", managementContainer);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(dashboardTabs, gridBagConstraints);
        dashboardTabs.getAccessibleContext().setAccessibleName("");

        greetingPanel.setLayout(new java.awt.GridLayout(3, 0));
        greetingPanel.add(filler1);

        greetingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greetingLabel.setText("INSERT GREETINGS HERE");
        greetingPanel.add(greetingLabel);
        greetingPanel.add(filler2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(greetingPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel collegesContainer;
    private javax.swing.JTabbedPane dashboardTabs;
    private javax.swing.JPanel enrollmentFormsContainer;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JPanel formPanelHolder;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel managementContainer;
    private javax.swing.JTabbedPane managementTabbedPanes;
    private javax.swing.JPanel programsContainer;
    private javax.swing.JPanel studentInformationContainer;
    private javax.swing.JToggleButton toggleFormButton;
    private javax.swing.JPanel toggleFormsPanelHolder;
    // End of variables declaration//GEN-END:variables
}
