/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaForms;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JTextField;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;



/**
 *
 * @author John-Ronan Beira
 */
public class templateForms extends javax.swing.JPanel {

    /**
     * Creates new form templateForms
     */
    public templateForms() {
        initComponents();
        applyIDFormat(idNumberField);
    }
    
    private void applyIDFormat(JTextField idNumberValue) {
    ((AbstractDocument) idNumberValue.getDocument()).setDocumentFilter(new DocumentFilter() {
        @Override
        public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            String currentText = fb.getDocument().getText(0, fb.getDocument().getLength());
            String newText = currentText.substring(0, offset) + text + currentText.substring(offset + length);

            // Remove non-digit characters
            newText = newText.replaceAll("[^\\d]", "");

            // Limit to 8 digits only
            newText = newText.substring(0, Math.min(newText.length(), 8));

            // Auto-format with dash
            if (newText.length() > 4) {
                newText = newText.substring(0, 4) + "-" + newText.substring(4);
            }

            fb.replace(0, fb.getDocument().getLength(), newText, attrs);
        }
    });

    // Ensure formatting when focus is lost
    idNumberValue.addFocusListener(new FocusAdapter() {
        @Override
        public void focusLost(FocusEvent evt) {
            formatID(idNumberValue);
        }
    });
}
    
    private void formatID(JTextField field) {
    String text = field.getText().replaceAll("[^\\d]", ""); // Remove non-digits
    while (text.length() < 8) {
        text = "0" + text; // Pad with leading zeros
    }
    field.setText(text.substring(0, 4) + "-" + text.substring(4));
}


 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formContentsPanel = new javax.swing.JPanel();
        firstLineContent = new javax.swing.JPanel();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        firstNameLabel = new javax.swing.JLabel();
        middleNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        genderLabel = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        yearLevelLabel = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jComboBox1 = new javax.swing.JComboBox<>();
        collegeNameLabel = new javax.swing.JLabel();
        collegeComboBox = new javax.swing.JComboBox<>();
        programNameLabel = new javax.swing.JLabel();
        programComboBox = new javax.swing.JComboBox<>();
        selectedCollegeLabel = new javax.swing.JLabel();
        selectedProgramLabel = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        filler8 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        secondLinePanelHolder = new javax.swing.JPanel();
        idNumberLabel = new javax.swing.JLabel();
        idNumberField = new javax.swing.JTextField();
        allowIdEdit = new javax.swing.JCheckBox();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        formLowerPanel = new javax.swing.JPanel();
        discardButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        jSeparator6 = new javax.swing.JSeparator();
        formHeaderPanel = new javax.swing.JPanel();
        // Resize the icon before setting it
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/resources/images/dog.png"));
        Image scaledImage = originalIcon.getImage().getScaledInstance(128, 128, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(scaledImage);
        formHeaderTitle = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        formContentsPanel.setBackground(new java.awt.Color(255, 255, 255));
        formContentsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        formContentsPanel.setLayout(new java.awt.GridBagLayout());

        firstLineContent.setOpaque(false);
        firstLineContent.setLayout(new java.awt.GridBagLayout());

        firstNameField.setBackground(new java.awt.Color(242, 242, 242));
        firstNameField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(firstNameField, gridBagConstraints);

        lastNameField.setBackground(new java.awt.Color(242, 242, 242));
        lastNameField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(lastNameField, gridBagConstraints);

        firstNameLabel.setText("First Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(firstNameLabel, gridBagConstraints);

        middleNameLabel.setText("Middle Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(middleNameLabel, gridBagConstraints);

        lastNameLabel.setText("Last Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(lastNameLabel, gridBagConstraints);

        middleNameField.setBackground(new java.awt.Color(242, 242, 242));
        middleNameField.setColumns(20);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(middleNameField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(filler2, gridBagConstraints);

        genderLabel.setText("Gender:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(genderLabel, gridBagConstraints);

        genderComboBox.setBackground(new java.awt.Color(242, 242, 242));
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Gender", "Male", "Female" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(genderComboBox, gridBagConstraints);

        yearLevelLabel.setText("Year Level:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(yearLevelLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(filler5, gridBagConstraints);

        jComboBox1.setBackground(new java.awt.Color(242, 242, 242));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Year Level", "1", "2", "3", "4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(jComboBox1, gridBagConstraints);

        collegeNameLabel.setText("College:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(collegeNameLabel, gridBagConstraints);

        collegeComboBox.setBackground(new java.awt.Color(242, 242, 242));
        collegeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select College" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(collegeComboBox, gridBagConstraints);

        programNameLabel.setText("Program:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(programNameLabel, gridBagConstraints);

        programComboBox.setBackground(new java.awt.Color(242, 242, 242));
        programComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Program" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(programComboBox, gridBagConstraints);

        selectedCollegeLabel.setFont(selectedCollegeLabel.getFont().deriveFont(selectedCollegeLabel.getFont().getStyle() | java.awt.Font.BOLD, selectedCollegeLabel.getFont().getSize()+2));
        selectedCollegeLabel.setText("PLEASE SELECT COLLEGE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(selectedCollegeLabel, gridBagConstraints);

        selectedProgramLabel.setFont(selectedProgramLabel.getFont().deriveFont(selectedProgramLabel.getFont().getStyle() | java.awt.Font.BOLD, selectedProgramLabel.getFont().getSize()+2));
        selectedProgramLabel.setText("PLEASE SELECT PROGRAM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        firstLineContent.add(selectedProgramLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        firstLineContent.add(filler3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.2;
        firstLineContent.add(filler7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.weighty = 0.1;
        firstLineContent.add(filler8, gridBagConstraints);

        secondLinePanelHolder.setOpaque(false);
        secondLinePanelHolder.setLayout(new java.awt.GridBagLayout());

        idNumberLabel.setText("ID Number:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        secondLinePanelHolder.add(idNumberLabel, gridBagConstraints);

        idNumberField.setBackground(new java.awt.Color(242, 242, 242));
        idNumberField.setColumns(9);
        idNumberField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idNumberField.setText("0000-0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        secondLinePanelHolder.add(idNumberField, gridBagConstraints);

        allowIdEdit.setText("Update Student ID");
        allowIdEdit.setToolTipText("Toggles between selecting students through their ID Numbers or Updating the selected student's ID Number");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        secondLinePanelHolder.add(allowIdEdit, gridBagConstraints);
        allowIdEdit.setVisible(false);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        firstLineContent.add(secondLinePanelHolder, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        formContentsPanel.add(firstLineContent, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 0.1;
        formContentsPanel.add(filler6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(formContentsPanel, gridBagConstraints);

        formLowerPanel.setLayout(new java.awt.GridBagLayout());

        discardButton.setBackground(new java.awt.Color(255, 153, 153));
        discardButton.setFont(discardButton.getFont().deriveFont(discardButton.getFont().getStyle() | java.awt.Font.BOLD));
        discardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/delivery-box.png"))); // NOI18N
        discardButton.setText("Discard Progress");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        formLowerPanel.add(discardButton, gridBagConstraints);

        createButton.setBackground(new java.awt.Color(153, 255, 153));
        createButton.setFont(createButton.getFont().deriveFont(createButton.getFont().getStyle() | java.awt.Font.BOLD));
        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/add.png"))); // NOI18N
        createButton.setText("Confirm Enrollment");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        formLowerPanel.add(createButton, gridBagConstraints);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        formLowerPanel.add(jSeparator2, gridBagConstraints);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
        formLowerPanel.add(jSeparator3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        formLowerPanel.add(jSeparator4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        formLowerPanel.add(jSeparator5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        formLowerPanel.add(filler4, gridBagConstraints);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        formLowerPanel.add(jSeparator6, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(formLowerPanel, gridBagConstraints);

        formHeaderPanel.setLayout(new java.awt.GridBagLayout());

        formHeaderTitle.setFont(formHeaderTitle.getFont().deriveFont(formHeaderTitle.getFont().getStyle() | java.awt.Font.BOLD, formHeaderTitle.getFont().getSize()+12));
        formHeaderTitle.setText("LUPINBRIDGE UNIVERSITY ENROLLMENT FORM");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        formHeaderPanel.add(formHeaderTitle, gridBagConstraints);
        formHeaderTitle.setIcon(resizedIcon); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(formHeaderPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox allowIdEdit;
    protected javax.swing.JComboBox<String> collegeComboBox;
    protected javax.swing.JLabel collegeNameLabel;
    protected javax.swing.JButton createButton;
    protected javax.swing.JButton discardButton;
    protected javax.swing.Box.Filler filler1;
    protected javax.swing.Box.Filler filler2;
    protected javax.swing.Box.Filler filler3;
    protected javax.swing.Box.Filler filler4;
    protected javax.swing.Box.Filler filler5;
    protected javax.swing.Box.Filler filler6;
    protected javax.swing.Box.Filler filler7;
    protected javax.swing.Box.Filler filler8;
    protected javax.swing.JPanel firstLineContent;
    protected javax.swing.JTextField firstNameField;
    protected javax.swing.JLabel firstNameLabel;
    protected javax.swing.JPanel formContentsPanel;
    protected javax.swing.JPanel formHeaderPanel;
    protected javax.swing.JLabel formHeaderTitle;
    protected javax.swing.JPanel formLowerPanel;
    protected javax.swing.JComboBox<String> genderComboBox;
    protected javax.swing.JLabel genderLabel;
    protected javax.swing.JTextField idNumberField;
    protected javax.swing.JLabel idNumberLabel;
    protected javax.swing.JComboBox<String> jComboBox1;
    protected javax.swing.JSeparator jSeparator2;
    protected javax.swing.JSeparator jSeparator3;
    protected javax.swing.JSeparator jSeparator4;
    protected javax.swing.JSeparator jSeparator5;
    protected javax.swing.JSeparator jSeparator6;
    protected javax.swing.JTextField lastNameField;
    protected javax.swing.JLabel lastNameLabel;
    protected javax.swing.JTextField middleNameField;
    protected javax.swing.JLabel middleNameLabel;
    protected javax.swing.JComboBox<String> programComboBox;
    protected javax.swing.JLabel programNameLabel;
    protected javax.swing.JPanel secondLinePanelHolder;
    protected javax.swing.JLabel selectedCollegeLabel;
    protected javax.swing.JLabel selectedProgramLabel;
    protected javax.swing.JLabel yearLevelLabel;
    // End of variables declaration//GEN-END:variables
}
