/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaForms;

import java.awt.event.FocusEvent;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author John-Ronan Beira
 */
public class templateFeedbackModalForms extends javax.swing.JDialog {

    /**
     * Creates new form templateFeedbackModalForms
     * @param parent
     * @param modal
     */
    public templateFeedbackModalForms(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        StyledDocument documents = feedbackTextPane.getStyledDocument();
        SimpleAttributeSet attributeSet = new SimpleAttributeSet();
        StyleConstants.setAlignment(attributeSet, StyleConstants.ALIGN_JUSTIFIED);
        documents.setParagraphAttributes(0, documents.getLength(), attributeSet, false);
        
        URL iconUrl = getClass().getResource("/resources/images/feedback.png");
        ImageIcon logo = new ImageIcon(iconUrl);
        setIconImage(logo.getImage());
        setResizable(false);
        declineButton.requestFocusInWindow(FocusEvent.Cause.ACTIVATION);
    }

    //getters
    public javax.swing.JTextPane getFeedbackTextPane() {
        return feedbackTextPane;
    }

    public javax.swing.JButton getConfirmButton() {
        return confirmButton;
    }
    
    public javax.swing.JButton getDeclineButton() {
        return declineButton;
    }
    
    public javax.swing.JScrollPane getJScrollPane1() {
        return jScrollPane1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        feedbackPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        feedbackTextPane = new javax.swing.JTextPane();
        buttonPanel = new javax.swing.JPanel();
        declineButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 200));
        setPreferredSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        feedbackPanel.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        feedbackTextPane.setEditable(false);
        feedbackTextPane.setFocusable(false);
        jScrollPane1.setViewportView(feedbackTextPane);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        feedbackPanel.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(feedbackPanel, gridBagConstraints);

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        declineButton.setBackground(new java.awt.Color(255, 153, 153));
        declineButton.setText("I'll double check");
        declineButton.setDoubleBuffered(true);
        declineButton.setFocusCycleRoot(true);
        declineButton.setFocusTraversalPolicyProvider(true);
        declineButton.setNextFocusableComponent(confirmButton);
        declineButton.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        buttonPanel.add(declineButton, gridBagConstraints);

        confirmButton.setBackground(new java.awt.Color(153, 255, 153));
        confirmButton.setText("Got it Boss!");
        confirmButton.setDefaultCapable(false);
        confirmButton.setNextFocusableComponent(declineButton);
        confirmButton.setRequestFocusEnabled(false);
        confirmButton.setRolloverEnabled(false);
        confirmButton.setVerifyInputWhenFocusTarget(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        buttonPanel.add(confirmButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.weightx = 0.1;
        buttonPanel.add(filler1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(buttonPanel, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(templateFeedbackModalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(templateFeedbackModalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(templateFeedbackModalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(templateFeedbackModalForms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                templateFeedbackModalForms dialog = new templateFeedbackModalForms(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JButton declineButton;
    private javax.swing.JPanel feedbackPanel;
    private javax.swing.JTextPane feedbackTextPane;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
